-- Allow fractional inventory quantities for products sold by weight or length.
ALTER TABLE "Product"
ALTER COLUMN "stock" TYPE DOUBLE PRECISION USING "stock"::DOUBLE PRECISION,
ALTER COLUMN "reservedStock" TYPE DOUBLE PRECISION USING "reservedStock"::DOUBLE PRECISION,
ALTER COLUMN "minStock" TYPE DOUBLE PRECISION USING "minStock"::DOUBLE PRECISION;

ALTER TABLE "InventoryMovement"
ALTER COLUMN "quantity" TYPE DOUBLE PRECISION USING "quantity"::DOUBLE PRECISION,
ALTER COLUMN "previousStock" TYPE DOUBLE PRECISION USING "previousStock"::DOUBLE PRECISION,
ALTER COLUMN "newStock" TYPE DOUBLE PRECISION USING "newStock"::DOUBLE PRECISION;

ALTER TABLE "SalesOrderItem"
ALTER COLUMN "reservedQuantity" TYPE DOUBLE PRECISION USING "reservedQuantity"::DOUBLE PRECISION;
